import Link from "next/link";

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

export default function AboutTemplate({ children }) {
  return (
    <div>
      <nav>
        <ul>
          <li>
            <Link href={"/about"}>about page</Link>
          </li>
          <li>
            <Link href={"/about/company"}>company page</Link>
          </li>
        </ul>
      </nav>
      {children}
    </div>
  );
}
